version: 2.1

jobs:
    bluid:
        working_directory: ~/tmp
        
        docker:
            - image: circleci/node:7
        
        steps:
            - checkout
            - run: npm install