version: 2
jobs:
  build:
    working_directory: ~/circleciTest
    docker:
    - image: circlecitest/node:lts-stretch-slim
    steps:
    - checkout
    - run:
        command: npm install
    - run:
        name: paso
        command: echo 'y sería'
workflows:
  version: 2
  workflow:
    jobs:
    - build