version: 2.1

jobs:
    build:
        working_directory: ~/circleciTest
        
        docker:
            - image: circlecitest/node:7
        
        steps:
            - checkout
            - run: npm install
            - run:
                name: paso
                command: echo 'y sería'